Blogs/urls.py
#Blogs
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "Blogs"

urlpatterns = [
    path("", views.blogs, name = "blogs"),
    path("<int:blog_id>", views.detail, name = "detail"),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from Portfolios import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.homepage, name = "homepage"),
    path('blogs/', include('Blogs.urls')),
    path("<int:member_id>", views.member_detail, name = "member_detail")
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blogs/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length = 50)
    author = models.CharField(max_length = 20)
    content = models.TextField()
    date = models.DateField(default = timezone.now())
    def __str__(self):
        return self.title

Portfolios/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    name = models.CharField(max_length = 25)
    description = models.CharField(max_length = 200)
    profile_picture = models.ImageField(upload_to = "media/portfolio/images/")
    def __str__(self):
        return self.name

Blogs/views.py
from django.shortcuts import render, get_object_or_404
from Portfolios import models
from Blogs import models as Blogmodels
# Create your views here.
def blogs(request):
    blog_count = Blogmodels.Blog.objects.count()
    members = models.Member.objects.all()
    first_five = Blogmodels.Blog.objects.order_by('-date')[:5]
    all_blogs = Blogmodels.Blog.objects.order_by('-date')
    return render (request, "blogs.html", {"members":members, "first_five":first_five, "all_blogs":all_blogs, "blog_count":blog_count})


def detail(request, blog_id):
    '''
    blog = Blogmodels.Blog.objects.all()
    for x in blog:
        if x.id == Blog_id:
            blog = x
            break
    '''
    blog = get_object_or_404(Blogmodels.Blog, pk = blog_id)
    return render (request, "detail.html", {"blog":blog})

Portfolios/views.py
from django.shortcuts import render, get_object_or_404
from .models import Member
from Blogs import models as Blogmodels

# Create your views here.
def homepage(request):
    members = Member.objects.all()
    blog_count = Blogmodels.Blog.objects.count()
    first_five = Blogmodels.Blog.objects.order_by('-date')[:5]
    return render (request, "homepage.html", {"members":members, "first_five":first_five, "blog_count":blog_count})

def member_detail(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    blogs = Blogmodels.Blog.objects.order_by('-date').filter(author=member.name)
    blog_count = blogs.count()
    return render (request, 'member-detail.html', {"member":member, "blogs":blogs, "blog_count":blog_count})

Blogs/templates/blogs.html
{% extends 'base.html' %}
<!doctype html>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <head>
<!-- Page Title -->
        {% block title-block %}
        <title>Our Blogs</title>
        {% endblock %}
{% block content %}
    </head>

    <body>
        <br>

<!-- Title -->
<div class = "container text-center">
    <h1 class="hmain">OUR BLOGS</h1>
    <br><br>

<!-- Authors' List (Scroller) -->
    <h2 class="container text-start" id="memnblog">Authors:</h2>
    <br>

    <div class="media-scroller-container">
        <div class="media-scroller image-cropper">
        {% for x in members %}
            <div class="media-element text-center ">
                <a href = "{% url 'member_detail' x.id %}">
                <img src = "{{ x.profile_picture.url }}" class="d-block mx-auto" height=200>
                <h4 id="memnblog" style="font-size: 1.75rem;">{{ x.name }}</h4>
                </a>
                <h6 id="hsub" style="font-size: 1.25rem;">{{ x.description|truncatechars:20 }}</h6>
            </div>
        {% endfor %}
        </div>
    </div>

    <br><br>
    <hr>

<!-- Blogs' Title and Count -->
    <h1 class = "container text-start" id="memnblog">All Blogs:</h1>
    <h5 class="container text-start" id="hsub">{{ blog_count }} blog{{ blog_count|pluralize }} written till date.</h5>

<!-- Blogs' List -->
    <div class="container">
    {% for blog in first_five %}
        <br><br>
        <h5>
            <div class="col text-start" id="hsub">
                On {{ blog.date|date:'dS M Y' }}, by <i>{{blog.author}}</i>
            </div>
            </h5>
            <a href = "{% url 'Blogs:detail' blog.id %}">
                <h4 class = "alert alert-success" id="memnblog" style="font-size:1.75rem">{{ blog.title }}</h4>
            </a>
            <h6 class="container text-start" id="hsub"><i>"{{ blog.content|striptags|truncatechars:75 }}</i></h6>
            <br>
        {% endfor %}
    </div>
</div>
{% endblock %}

    </body>
</docttype>

Blogs/templates/detail.html
{% extends 'base.html' %}
<!doctype html>
{% load static %}

<head>
<!-- Page Title -->
    {% block title-block %}
    <title>Blogs - {{ blog.title }}</title>
    {% endblock %}
{% block content %}
</head>

<body>

<br>

<!-- Blog Title -->
<div class = "container text-center" style="margin: 0 auto; max-width: 90%; min-width: 200px;">
<h1 class="hmain">{{ blog.title }}</h1>
<h4>

<!-- Date and Author -->
<div class="text-end">
     ~ On {{ blog.date|date:'dS M Y' }}, by <i>{{blog.author}}</i>
</div>
</h4>

<br><br><br><br>

<!-- Content -->
<h4 class="text-start" id="hsub">{{ blog.content|safe }}</h4>
</div>
{% endblock %}
</body>
</docttype>

Portfolios/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
  <meta name="title" content="Topkar Family">
  <meta name="description" content="Family portfolio of Topkar family.">
  <meta name="keywords" content="topCodegeek, Topkar, Ishaan Topkar">
  <meta name="robots" content="noindex, nofollow">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="language" content="English">

    {% block title-block %}{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'Handshake.png' %}">
    <!-- CSS: -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/styles.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Salsa&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@600&display=swap" rel="stylesheet">
  </head>

  <body>

<!-- Navbar: -->
<nav class="navbar navbar-expand navbar-light bg-warning">
  <!-- Nav-brand -->
  <div class="container-fluid justify-content-between align-items-center">
    <a class="navbar-brand" href="{% url 'homepage' %}" style="font-size: auto;">
      <img src="{% static 'portfolio/Handshake.png' %}" alt="Logo" width="24" height="24" class="d-inline-block align-text-top">
      <b><i>TOPKAR</i></b>
    </a>
  <!-- Faint Text -->
        <!-- (Removed) -->
    <!-- (removed 'un-official' text) -->

  <!-- Droupdown -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav  ms-auto me-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="btn btn-warning dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <b style="font-family: sans-serif, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">SOCIAL</b>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="https://github.com/topCodegeek" target="_blank">Github</a></li>
            <li><a class="dropdown-item" href="https://x.com/topCodegeek" target="_blank">Twitter</a></li>
            <li><a class="dropdown-item" href="https://forum.arduino.cc/u/ishaantopkar/" target="_blank">Arduino</a></li>
            <li><a class="dropdown-item" href="https://www.udemy.com/user/gauri-274/" target="_blank">Udemy</a></li>
          </ul>
  <!-- Button -->
        <li class="nav-item">
          <a class="btn btn-primary" href="{% url 'Blogs:blogs' %}" style="font-family: sans-serif, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">BLOGS</a>
        </li>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div style="min-height: 100vh;">

 <!-- Insert Block -->
{% block content %}{% endblock %}
</div>

<!-- End Credit -->
<br><br><br><hr>
<div class="alert alert-secondary">
<br>
<br>
<br>
  <div class="container text-center">
    <h6 class="container text-center" style="font-size: 1.2rem">&#9432; <i>Web Author: Ishaan Topkar</h6></i>
    <h6 style="font-size: 0.9rem">
      View This <a href="https://github.com/topCodegeek/Django-Personal-Portfolio" target="_blank">Project</a>
    </h6>
  </div>
</div>

    <!-- Popper and JS: -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>

Portfolios/templates/homepage.html
{% extends 'base.html' %}
<!doctype html>
    {% load static %}
    <head>
        <!-- Page Title -->
        {% block title-block %}
        <title>Topkar Family</title>
        {% endblock %}
    </head>
<body>
    {% block content %}
    <br>
    
<!-- Banner and Heading -->
        <img src = "{% static 'portfolio/WithDadas.png' %}" class="banner">
        <div class="alert alert-success custom-alert">    
              <h5 class="text-center" style="font-size: 1.9vw;">&#9432; AI Generated Image</h5>
        </div>
        <h1 class="container text-center hmain">TOPKAR FAMILY</h1>    
        <br>

<!-- Members Scroller -->
        <div class="container">
        <hr>

        <!-- Members' Title -->
        <h1 class="container text-start" id="memnblog">Members:</h1>
        <br><br>
        </div>
        <div class="media-scroller-container">
        <div class="media-scroller image-cropper">
            
        <!-- Members' List -->
        {% for x in members %}
            <div class="media-element text-center ">
                <a href = "{% url 'member_detail' x.id %}">
                <img src = "{{ x.profile_picture.url }}" class="d-block mx-auto" height=200>
                <h4 id="memnblog" style="font-size: 1.75rem;">{{ x.name }}</h4>
                </a>
                <h6 id="hsub" style="font-size: 1.25rem;">{{ x.description|truncatechars:20 }}</h6>
            </div>
        {% endfor %}
        </div>
        </div>
        <br><br>

<!-- Blogs -->
        <div class = "container text-center">
            <hr>

            <!-- Blogs' Title -->
            <h1 class = "container text-start" id="memnblog">Our Blogs:</h1>
            <h5 class="container text-start" id="hsub">{{ blog_count }} blog{{ blog_count|pluralize }} written till date.</h5>
            
            <!-- Blogs' List -->
            {% for blog in first_five %}
            <br><br>
            <h5>
            <div class="row">
                <div class="col text-start" id="hsub">
                    On {{ blog.date|date:'dS M Y' }}, by <i>{{blog.author}}</i>
                </div>
            </h5>            
            <a href = "{% url 'Blogs:detail' blog.id %}">
            <h4 class = "alert alert-success" id="memnblog" style="font-size:1.75rem">{{ blog.title }}</h4>
            </a>
            <h6 class="container text-start" id="hsub"><i>"{{ blog.content|striptags|truncatechars:75 }}</i></h6>
            <br>
            {% endfor %}
        </div>
{% endblock %}

</body>
</docttype>

Portfolios/templates/member-detail.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<head>
 {% block title-block %}
 <!-- Page Title -->
<title>{{ member.name }}</title>
{% endblock %}
</head>

{% block content %}
<body>
<br>

<!-- Title -->
<div class="container text-center image-cropper">
<br>
<img src = "{{ member.profile_picture.url }}" height=350>
<br>
<br>
<h5 class="hmain">{{ member.name }}</h5>
<h5 id="memnblog">{{ member.description }}</h5>
</div>

<!-- Blog Title -->
{% if blog_count > 0 %}
<hr>
<div class="container text-start">
<h2 id="memnblog">Blog{{ blog_count|pluralize }} by {{ member.name }}:</h2>
</div>
<br><br>

<!-- Blog List -->
{% for blog in blogs %}

<div class="container text-center image-cropper ">
<br>
<h5 class = "text-start" id="hsub">{{ blog.date|date:'dS M Y' }}</h5>            
<a href = "{% url 'Blogs:detail' blog.id %}">
    <h4 class = "alert alert-success" id="memnblog" style="font-size:1.75rem">{{ blog.title }}</h4>
</a>
<h6 class="container text-start" id="hsub"><i>"{{ blog.content|striptags|truncatechars:75 }}</i></h6>
</div>
<br>

{% endfor %}
{% endif %}
</body>
{% endblock %}
</docttype>